steps:
- name: 'gcr.io/cloud-builders/mvn'
  id: 'INSTALL'
  args: ['install']
- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  id: 'SCANNER'
  args:
  - '-Dsonar.host.url=https://sonarcloud.io'
  - '-Dsonar.login=a1395048df35e62623c804bcc8eff9b3e8b8234d'
  - '-Dsonar.projectKey=sb-junit'
  - '-Dsonar.organization=g33kzone'
  - '-Dsonar.sources=/workspace/target'
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']