steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['test']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']